### ISSUE TITLE
Create quick readme how to use this plugin

### ISSUE THREAD

**Issue by bluepuma77** [willsub/capacitor-ios-remote-notifications#1]
It would be great if you could provide a quick readme. Bullet points or `code snippets` should be enough:

1. How to build and add this to Capacitor?
2. What needs to be added on iOS part, besides Background Modes Capabilities?
3. How does the Javascript part work (init, permissions, listeners)?

Sorry @aparajita for not letting you off the hook yet 🤷 Happy to be your alpha tester!

As a web developer I have little to contribute here, I am trying to be a good web citizen, too ([Github](https://github.com/bluepuma77/traefik-best-practice)).

**Comment by aparajita** [comment]
I just don't have time right now, sorry.
